lulesh:
    build:
        variants: [ 'openmp' ]
        files: '@SRCPATH@/Makefile'
        make:
            target: ''
    run:
        program: '@SRCPATH@/lulesh2.0'
        iterate:
            n_mpi:
                values: [{op: 'powerof', of: 3}]
            n_omp:
                values: [2, 4, 8]

